import{createClient}from'https://esm.sh/@supabase/supabase-js@2.111.0';
const U='https://xgrfndfjqsqichvswtqh.supabase.co',K='sb_publishable_6_QzwzHMtpRwIRIlseHw5w_ecvV93fz',A=U+'/functions/v1/netbuilder-api',s=createClient(U,K);
let S=null,P=[],X=null,B=null,lastPrompt='';
const $=i=>document.getElementById(i);
const esc=t=>String(t||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const formatAI=t=>esc(t).replace(/\*\*(.+?)\*\*/g,'<strong>$1</strong>').replace(/^###\s+(.+)$/gm,'<h3>$1</h3>').replace(/^##\s+(.+)$/gm,'<h3>$1</h3>').replace(/^#\s+(.+)$/gm,'<h3>$1</h3>').replace(/\n/g,'<br>');
async function api(a,o={}){const h={...(o.headers||{}),'Content-Type':'application/json','Authorization':'Bearer '+S.access_token,'apikey':K},r=await fetch(A+'?action='+encodeURIComponent(a),{...o,headers:h}),d=await r.json();if(!r.ok)throw new Error(d.error||'NetBuilder API error');return d}
function app(){ $('login').classList.add('hidden');$('app').classList.remove('hidden');$('logout').classList.remove('hidden');$('userTag').textContent=S.user.email }
function login(){ $('login').classList.remove('hidden');$('app').classList.add('hidden');$('logout').classList.add('hidden');$('userTag').textContent='CEO Mode' }
async function health(){try{const d=await api('health');if(d.openai_reachable){$('aiStatus').textContent='Connected · '+d.model;$('aiStatus').className='success'}else{$('aiStatus').textContent=d.openai_configured?'Key detected · unavailable':'Not configured';$('aiStatus').className='error'}}catch(e){$('aiStatus').textContent='API error';$('aiStatus').className='error'}}
async function load(){try{const d=await api('projects');P=d.projects||[];$('projectList').innerHTML='';P.forEach(p=>{const b=document.createElement('button');b.textContent=p.name;b.dataset.letter=(p.name||'N').charAt(0).toUpperCase();b.dataset.status=p.status==='ready'?'Ready':p.status;b.addEventListener('click',()=>sel(p,b));$('projectList').appendChild(b)});if(P.length&&!X){const f=P.find(p=>p.slug==='autonet')||P[0],bs=[...$('projectList').querySelectorAll('button')];sel(f,bs[P.indexOf(f)])}}catch(e){$('projectList').innerHTML='<div class="error">'+esc(e.message)+'</div>';throw e}}
function sel(p,b){X=p;B=null;lastPrompt='';$('approveBtn').disabled=true;$('feedbackBtn').disabled=true;$('reviewNotes').value='';[...$('projectList').querySelectorAll('button')].forEach(x=>x.classList.remove('active'));if(b)b.classList.add('active');$('projectStatus').textContent=p.name+' · '+p.status;$('previewProject').textContent=p.name+' / Live Preview';$('buildMeta').textContent='Awaiting instruction';$('buildOutput').innerHTML='<div class="empty-state"><div class="empty-orb">N</div><h3>Your plan will appear here</h3><p>Tell NetBuilder what you want to create or change. You can write in English, Spanish or Spanglish.</p></div>'}
async function boot(){return Promise.allSettled([load(),health()])}
function setPlanning(){ $('createBuild').disabled=true;$('approveBtn').disabled=true;$('feedbackBtn').disabled=true;$('buildMeta').textContent='Generating with OpenAI…';$('buildOutput').innerHTML='<div class="empty-state"><div class="empty-orb">✦</div><h3>Designing the plan</h3><p>NetBuilder is analyzing architecture, guardrails and next actions.</p></div>' }
function showBuild(d){B=d.build;$('buildMeta').textContent='AI · '+(d.ai?.model||'OpenAI')+' · '+B.status;$('buildOutput').innerHTML='<h3>'+esc(X.name)+' Build Plan</h3><div>'+formatAI(B.summary)+'</div>';$('approveBtn').disabled=B.status!=='ready';$('feedbackBtn').disabled=B.status!=='ready'}
async function generate(prompt){setPlanning();try{const d=await api('build',{method:'POST',body:JSON.stringify({project_id:X.id,prompt})});showBuild(d)}catch(e){$('buildMeta').textContent='Generation failed';$('buildOutput').innerHTML='<p class="error">'+esc(e.message)+'</p>'}finally{$('createBuild').disabled=false}}
$('loginBtn').addEventListener('click',async()=>{$('loginMsg').textContent='Signing in…';$('loginMsg').className='message';const{data,error}=await s.auth.signInWithPassword({email:$('email').value.trim(),password:$('password').value});if(error){$('loginMsg').textContent=error.message;$('loginMsg').className='message error';return}S=data.session;app();await boot()});
$('logout').addEventListener('click',async()=>{await s.auth.signOut();S=null;X=null;B=null;login()});
$('refresh').addEventListener('click',async()=>{await boot()});
$('createBuild').addEventListener('click',async()=>{if(!X)return;const p=$('prompt').value.trim();if(!p)return;lastPrompt=p;$('reviewNotes').value='';$('approvalMsg').textContent='';await generate(p)});
$('feedbackBtn').addEventListener('click',async()=>{if(!B||!X)return;const note=$('reviewNotes').value.trim();if(!note){$('approvalMsg').textContent='Escribe primero los cambios que quieres revisar.';$('approvalMsg').className='message error';return}$('approvalMsg').textContent='';const revised=(lastPrompt||$('prompt').value.trim())+'\n\nREVISIÓN DEL CEO: '+note+'\nDevuelve el plan revisado en español y no publiques nada.';lastPrompt=revised;await generate(revised)});
$('approveBtn').addEventListener('click',async()=>{if(!B)return;$('approveBtn').disabled=true;$('feedbackBtn').disabled=true;$('approvalMsg').textContent='Approving…';$('approvalMsg').className='message';try{const review_note=$('reviewNotes').value.trim();const d=await api('approve',{method:'POST',body:JSON.stringify({build_id:B.id,review_note})});B=d.build;$('approvalMsg').textContent='✓ Plan aprobado por CEO. Production remains protected until the execution stage.';$('approvalMsg').className='message success';$('buildMeta').textContent='Approved · waiting for execution'}catch(e){$('approvalMsg').textContent=e.message;$('approvalMsg').className='message error';$('approveBtn').disabled=false;$('feedbackBtn').disabled=false}});
const{data:{session:e}}=await s.auth.getSession();if(e){S=e;app();await boot()}else login();