import{createClient}from'https://esm.sh/@supabase/supabase-js@2.111.0';
const U='https://xgrfndfjqsqichvswtqh.supabase.co',K='sb_publishable_6_QzwzHMtpRwIRIlseHw5w_ecvV93fz',A=U+'/functions/v1/netbuilder-api',s=createClient(U,K);let S=null,P=[],X=null,B=null;const $=i=>document.getElementById(i);const esc=t=>String(t||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
async function api(a,o={}){const h={...(o.headers||{}),'Content-Type':'application/json','Authorization':'Bearer '+S.access_token,'apikey':K},r=await fetch(A+'?action='+encodeURIComponent(a),{...o,headers:h}),d=await r.json();if(!r.ok)throw new Error(d.error||'Error de NetBuilder');return d}
function app(){ $('login').classList.add('hidden');$('app').classList.remove('hidden');$('logout').classList.remove('hidden');$('userTag').textContent=S.user.email}
function login(){ $('login').classList.remove('hidden');$('app').classList.add('hidden');$('logout').classList.add('hidden');$('userTag').textContent='CEO Mode'}
async function health(){try{const d=await api('health');$('aiStatus').textContent=d.openai_configured?'✓ '+d.model:'no configurada';$('aiStatus').className=d.openai_configured?'ok success':'ok error'}catch(e){$('aiStatus').textContent='error de conexión';$('aiStatus').className='ok error'}}
async function load(){const d=await api('projects');P=d.projects||[];$('projectList').innerHTML='';P.forEach(p=>{const b=document.createElement('button');b.textContent=p.name;b.addEventListener('click',()=>sel(p,b));$('projectList').appendChild(b)});if(P.length&&!X){const f=P.find(p=>p.slug==='motonet')||P[0],bs=[...$('projectList').querySelectorAll('button')];sel(f,bs[P.indexOf(f)])}}
function sel(p,b){X=p;B=null;$('approveBtn').disabled=true;[...$('projectList').querySelectorAll('button')].forEach(x=>x.classList.remove('active'));if(b)b.classList.add('active');$('projectStatus').textContent=p.name+' · '+p.status}
$('loginBtn').addEventListener('click',async()=>{$('loginMsg').textContent='Entrando…';const{data,error}=await s.auth.signInWithPassword({email:$('email').value.trim(),password:$('password').value});if(error){$('loginMsg').textContent=error.message;$('loginMsg').className='error';return}S=data.session;app();await Promise.all([load(),health()])});
$('logout').addEventListener('click',async()=>{await s.auth.signOut();S=null;X=null;B=null;login()});
$('refresh').addEventListener('click',async()=>{await Promise.all([load(),health()])});
$('createBuild').addEventListener('click',async()=>{if(!X)return;const p=$('prompt').value.trim();if(!p)return;$('createBuild').disabled=true;$('buildOutput').innerHTML='<p>OpenAI preparando el plan…</p>';try{const d=await api('build',{method:'POST',body:JSON.stringify({project_id:X.id,prompt:p})});B=d.build;$('buildOutput').innerHTML='<h3>'+esc(X.name)+'</h3><p><b>Estado:</b> '+esc(B.status)+' · <b>AI:</b> '+esc(d.ai?.model||'')+'</p><div>'+esc(B.summary).replace(/\n/g,'<br>')+'</div>';$('approveBtn').disabled=B.status!=='ready'}catch(e){$('buildOutput').innerHTML='<p class="error">'+esc(e.message)+'</p>'}finally{$('createBuild').disabled=false}});
$('approveBtn').addEventListener('click',async()=>{if(!B)return;$('approveBtn').disabled=true;try{const d=await api('approve',{method:'POST',body:JSON.stringify({build_id:B.id})});B=d.build;$('buildOutput').innerHTML+='<p class="success"><b>✓ Plan aprobado por CEO.</b></p>'}catch(e){$('buildOutput').innerHTML+='<p class="error">'+esc(e.message)+'</p>'}});
const{data:{session:e}}=await s.auth.getSession();if(e){S=e;app();await Promise.all([load(),health()])}else login();