import{createClient}from'https://esm.sh/@supabase/supabase-js@2.111.0';
const U='https://xgrfndfjqsqichvswtqh.supabase.co',K='sb_publishable_6_QzwzHMtpRwIRIlseHw5w_ecvV93fz',A=U+'/functions/v1/netbuilder-api',s=createClient(U,K);
let S=null,P=[],X=null,B=null,lastPrompt='',GH=false,EXEC=null;
const $=i=>document.getElementById(i);
const esc=t=>String(t||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const formatAI=t=>esc(t).replace(/\*\*(.+?)\*\*/g,'<strong>$1</strong>').replace(/^###\s+(.+)$/gm,'<h3>$1</h3>').replace(/^##\s+(.+)$/gm,'<h3>$1</h3>').replace(/^#\s+(.+)$/gm,'<h3>$1</h3>').replace(/\n/g,'<br>');
async function api(a,o={}){const{query,...opts}=o;const qs=new URLSearchParams({action:a});if(query)Object.entries(query).forEach(([k,v])=>qs.set(k,String(v)));const h={...(opts.headers||{}),'Content-Type':'application/json','Authorization':'Bearer '+S.access_token,'apikey':K},r=await fetch(A+'?'+qs.toString(),{...opts,headers:h}),d=await r.json();if(!r.ok)throw new Error(d.error||'NetBuilder API error');return d}
async function copyToClipboard(text,button){if(!text)return;const original=button.innerHTML;try{await navigator.clipboard.writeText(text);button.innerHTML='✓ Copied';button.classList.add('copied')}catch(e){const ta=document.createElement('textarea');ta.value=text;ta.style.position='fixed';ta.style.opacity='0';document.body.appendChild(ta);ta.select();document.execCommand('copy');ta.remove();button.innerHTML='✓ Copied';button.classList.add('copied')}setTimeout(()=>{button.innerHTML=original;button.classList.remove('copied')},1600)}
function renderExecution(execution){const map=execution?.project_map||'';$('executionLog').innerHTML='<div class="execution-result"><div class="execution-result-head"><b>✓ Project Map Ready</b><div class="execution-head-actions"><span>'+esc(execution?.model||'OpenAI')+'</span><button id="copyExecutionBtn" class="copy-btn" type="button" title="Copy Project Map" aria-label="Copy Project Map">⧉ Copy</button></div></div><div>'+formatAI(map)+'</div></div>';const btn=$('copyExecutionBtn');if(btn)btn.addEventListener('click',()=>copyToClipboard(map,btn))}
function app(){ $('login').classList.add('hidden');$('app').classList.remove('hidden');$('logout').classList.remove('hidden');$('userTag').textContent=S.user.email }
function login(){ $('login').classList.remove('hidden');$('app').classList.add('hidden');$('logout').classList.add('hidden');$('userTag').textContent='CEO Mode' }
async function health(){try{const d=await api('health');if(d.openai_reachable){$('aiStatus').textContent='Connected · '+d.model;$('aiStatus').className='success'}else{$('aiStatus').textContent=d.openai_configured?'Key detected · unavailable':'Not configured';$('aiStatus').className='error'}}catch(e){$('aiStatus').textContent='API error';$('aiStatus').className='error'}}
function setExecutionButtons(){const approved=Boolean(B&&B.status==='approved');$('executeBtn').disabled=!(approved&&GH);$('viewProgressBtn').disabled=!EXEC;$('pauseBtn').disabled=true;if(approved&&!GH){$('executionLog').innerHTML='<div class="execution-empty">Plan aprobado. Falta autorizar GitHub para iniciar el análisis read-only.</div>'}else if(approved&&GH&&!EXEC){$('executionLog').innerHTML='<div class="execution-ready">✓ Plan aprobado · GitHub conectado · Safe Mode listo.</div>'}}
async function githubStatus(){if(!X)return;try{const d=await api('github_status',{method:'POST',body:JSON.stringify({project_id:X.id})});GH=Boolean(d.connected);$('githubStatus').textContent=GH?'Connected · read-only repository access verified':(d.detail||'Authorization required');$('githubStatus').className=GH?'success':'muted';$('githubDot').className='connection-dot '+(GH?'connected':'');$('connectGitHubBtn').textContent=GH?'✓ GitHub Connected':'Connect GitHub';$('repoAccessBadge').textContent=GH?'READ ONLY':'LOCKED';$('repoAccessBadge').className=GH?'connected-badge':'';setExecutionButtons()}catch(e){GH=false;$('githubStatus').textContent='GitHub access unavailable';$('githubStatus').className='error';$('repoAccessBadge').textContent='LOCKED';setExecutionButtons()}}
async function loadLatestBuild(p){try{const d=await api('builds',{query:{project_id:p.id}});const builds=d.builds||[];const latest=builds.find(x=>['approved','ready'].includes(x.status))||builds[0];if(!latest)return;B=latest;lastPrompt=B.prompt||'';$('buildMeta').textContent=(B.status==='approved'?'Approved':'Saved')+' · '+B.status;$('buildOutput').innerHTML='<h3>'+esc(p.name)+' Build Plan</h3><div>'+formatAI(B.summary||'')+'</div>';$('approveBtn').disabled=B.status!=='ready';$('feedbackBtn').disabled=B.status!=='ready';if(B.status==='approved'){$('approvalMsg').textContent='✓ Existing CEO-approved plan recovered.';$('approvalMsg').className='message success'}setExecutionButtons()}catch(e){console.warn('latest build',e)}}
async function load(){try{const d=await api('projects');P=d.projects||[];$('projectList').innerHTML='';P.forEach(p=>{const b=document.createElement('button');b.textContent=p.name;b.dataset.letter=(p.name||'N').charAt(0).toUpperCase();b.dataset.status=p.status==='ready'?'Ready':p.status;b.addEventListener('click',()=>sel(p,b));$('projectList').appendChild(b)});if(P.length&&!X){const f=P.find(p=>p.slug==='autonet')||P[0],bs=[...$('projectList').querySelectorAll('button')];await sel(f,bs[P.indexOf(f)])}}catch(e){$('projectList').innerHTML='<div class="error">'+esc(e.message)+'</div>';throw e}}
async function sel(p,b){X=p;B=null;EXEC=null;GH=false;lastPrompt='';$('approveBtn').disabled=true;$('feedbackBtn').disabled=true;$('executeBtn').disabled=true;$('viewProgressBtn').disabled=true;$('reviewNotes').value='';$('approvalMsg').textContent='';[...$('projectList').querySelectorAll('button')].forEach(x=>x.classList.remove('active'));if(b)b.classList.add('active');$('projectStatus').textContent=p.name+' · '+p.status;$('previewProject').textContent=p.name+' / Live Preview';$('repoName').textContent=p.source_repo||'Repository not registered';$('buildMeta').textContent='Awaiting instruction';$('buildOutput').innerHTML='<div class="empty-state"><div class="empty-orb">N</div><h3>Your plan will appear here</h3><p>Tell NetBuilder what you want to create or change. You can write in English, Spanish or Spanglish.</p></div>';$('executionLog').innerHTML='<div class="execution-empty">Checking approved plan and repository access…</div>';await Promise.allSettled([loadLatestBuild(p),githubStatus()]);setExecutionButtons()}
async function boot(){return Promise.allSettled([load(),health()])}
function setPlanning(){ $('createBuild').disabled=true;$('approveBtn').disabled=true;$('feedbackBtn').disabled=true;$('buildMeta').textContent='Generating with OpenAI…';$('buildOutput').innerHTML='<div class="empty-state"><div class="empty-orb">✦</div><h3>Designing the plan</h3><p>NetBuilder is analyzing architecture, guardrails and next actions.</p></div>' }
function showBuild(d){B=d.build;EXEC=null;$('buildMeta').textContent='AI · '+(d.ai?.model||'OpenAI')+' · '+B.status;$('buildOutput').innerHTML='<h3>'+esc(X.name)+' Build Plan</h3><div>'+formatAI(B.summary)+'</div>';$('approveBtn').disabled=B.status!=='ready';$('feedbackBtn').disabled=B.status!=='ready';setExecutionButtons()}
async function generate(prompt){setPlanning();try{const d=await api('build',{method:'POST',body:JSON.stringify({project_id:X.id,prompt})});showBuild(d)}catch(e){$('buildMeta').textContent='Generation failed';$('buildOutput').innerHTML='<p class="error">'+esc(e.message)+'</p>'}finally{$('createBuild').disabled=false}}
$('loginBtn').addEventListener('click',async()=>{$('loginMsg').textContent='Signing in…';$('loginMsg').className='message';const{data,error}=await s.auth.signInWithPassword({email:$('email').value.trim(),password:$('password').value});if(error){$('loginMsg').textContent=error.message;$('loginMsg').className='message error';return}S=data.session;app();await boot()});
$('logout').addEventListener('click',async()=>{await s.auth.signOut();S=null;X=null;B=null;GH=false;EXEC=null;login()});
$('refresh').addEventListener('click',async()=>{await boot()});
$('createBuild').addEventListener('click',async()=>{if(!X)return;const p=$('prompt').value.trim();if(!p)return;lastPrompt=p;$('reviewNotes').value='';$('approvalMsg').textContent='';await generate(p)});
$('feedbackBtn').addEventListener('click',async()=>{if(!B||!X)return;const note=$('reviewNotes').value.trim();if(!note){$('approvalMsg').textContent='Escribe primero los cambios que quieres revisar.';$('approvalMsg').className='message error';return}$('approvalMsg').textContent='';const revised=(lastPrompt||$('prompt').value.trim())+'\n\nREVISIÓN DEL CEO: '+note+'\nDevuelve el plan revisado en español y no publiques nada.';lastPrompt=revised;await generate(revised)});
$('approveBtn').addEventListener('click',async()=>{if(!B)return;$('approveBtn').disabled=true;$('feedbackBtn').disabled=true;$('approvalMsg').textContent='Approving…';$('approvalMsg').className='message';try{const review_note=$('reviewNotes').value.trim();const d=await api('approve',{method:'POST',body:JSON.stringify({build_id:B.id,review_note})});B=d.build;$('approvalMsg').textContent='✓ Plan aprobado por CEO. Production remains protected until the execution stage.';$('approvalMsg').className='message success';$('buildMeta').textContent='Approved · waiting for execution';setExecutionButtons()}catch(e){$('approvalMsg').textContent=e.message;$('approvalMsg').className='message error';$('approveBtn').disabled=false;$('feedbackBtn').disabled=false}});
$('connectGitHubBtn').addEventListener('click',async()=>{if(!X)return;await githubStatus();if(!GH){$('executionLog').innerHTML='<div class="execution-warning"><b>One-time GitHub authorization required.</b><br>NetBuilder necesita un acceso read-only guardado en el servidor. Se abrirá GitHub para crear la autorización; no pegues claves dentro del navegador de NetBuilder.</div>';window.open('https://github.com/settings/personal-access-tokens/new','_blank','noopener,noreferrer')}});
$('executeBtn').addEventListener('click',async()=>{if(!B||B.status!=='approved'||!GH||!X)return;$('executeBtn').disabled=true;$('executionLog').innerHTML='<div class="execution-running"><b>Running Safe Execution…</b><br>Importando '+esc(X.source_repo||X.name)+' en modo read-only, analizando arquitectura y creando Project Map.</div>';$('executionMode').textContent='ANALYZING · READ ONLY';try{const d=await api('execute',{method:'POST',body:JSON.stringify({build_id:B.id,project_id:X.id})});EXEC=d.execution;$('executionMode').textContent='READ-ONLY COMPLETE';renderExecution(EXEC);$('viewProgressBtn').disabled=false;$('repoAccessBadge').textContent='IMPORTED';$('repoAccessBadge').className='connected-badge'}catch(e){$('executionMode').textContent='READ-ONLY SAFE MODE';$('executionLog').innerHTML='<div class="execution-warning"><b>Execution blocked safely.</b><br>'+esc(e.message)+'</div>'}finally{setExecutionButtons()}});
$('viewProgressBtn').addEventListener('click',()=>{$('executionLog').scrollIntoView({behavior:'smooth',block:'center'})});
const{data:{session:e}}=await s.auth.getSession();if(e){S=e;app();await boot()}else login();